# Default values for freetak.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/freetakteam/freetakserver
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

freetakserver:
  args: ""
  connectionMessage: ""
  saveCotToDb: true
  dataPackageHost: "0.0.0.0"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi

readinessProbe:
  tcpSocket:
    port: clientport
  initialDelaySeconds: 30
  periodSeconds: 30
  failureThreshold: 10
  successThreshold: 1
  timeoutSeconds: 3
livenessProbe:
  tcpSocket:
    port: clientport
  initialDelaySeconds: 30
  periodSeconds: 30
  failureThreshold: 10
  successThreshold: 1
  timeoutSeconds: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - name: datadir
    emptyDir: {}

volumeMounts:
  - name: datadir
    mountPath: "/data"

nodeSelector: {}

tolerations: []

affinity: {}

ui:
  enabled: true
  image:
    repository: ghcr.io/freetakteam/ui
    pullPolicy: IfNotPresent
    tag: "latest"
  readinessProbe:
    tcpSocket:
      port: clientport
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 10
    successThreshold: 1
    timeoutSeconds: 3
  livenessProbe:
    tcpSocket:
      port: clientport
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 10
    successThreshold: 1
    timeoutSeconds: 3
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  volumeMounts:
    - name: datadir
      mountPath: "/data"
